// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgvnhcqxbmwtufxdvepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtndm5oY3F4Ym13dHVmeGR2ZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDk3NzQsImV4cCI6MjA3MjY4NTc3NH0.Ia1AJnWrYaKTZ_7qmqYd_idCzv2p0eXzUHygOPrlp-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});